upstream backend-spring-rest {
    server backend-spring:8080;
}

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name vnptbacninh.com www.vnptbacninh.com;
    return 301 https://$host$request_uri;
}

# HTTPS Server
server {
    listen 443 ssl;
    server_name vnptbacninh.com www.vnptbacninh.com;

    ssl_certificate /etc/letsencrypt/live/vnptbacninh.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vnptbacninh.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

	location /api {
		proxy_pass http://backend-spring:8080;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;

		if ($http_origin ~* (http://localhost:3000|https://vnptbacninh.com)) {
			add_header 'Access-Control-Allow-Origin' "$http_origin" always;
			add_header 'Access-Control-Allow-Credentials' 'true' always;
			add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
			add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type, X-Requested-With' always;
		}

		if ($request_method = 'OPTIONS') {
			add_header 'Access-Control-Max-Age' 3600;
			add_header 'Content-Length' 0;
			add_header 'Content-Type' 'text/plain charset=UTF-8';
			return 204;
		}
	}

    location /storage {
        try_files $uri $uri/ @proxy;
    }

    location @proxy {
        proxy_pass http://backend-spring:8080;
    }
}
