# Redirect HTTP → HTTPS
server {
    listen 80;
    server_name vnptbacninh.com www.vnptbacninh.com;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name vnptbacninh.com www.vnptbacninh.com;

    ssl_certificate /etc/letsencrypt/live/vnptbacninh.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/vnptbacninh.com/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

	location /api/ {
		proxy_pass http://backend-spring:8080/api/;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
	}
	
	location /storage/ {
        alias /uploads/;                    # 👈 Trỏ tới thư mục mount trong container nginx
        autoindex on;                       # (tùy chọn, cho phép duyệt file)
        access_log off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
