version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: smartdb
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: smart123
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smartnet

  backend-spring:
    build:
      context: ../smart-java-spring-final
      dockerfile: Dockerfile
    container_name: backend-spring
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/smartdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: smartuser
      SPRING_DATASOURCE_PASSWORD: smart123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
    networks:
      - smartnet
    expose:
      - "8080"

  frontend-react:
    build:
      context: ../smart-react-vite-final
      dockerfile: Dockerfile
    container_name: frontend-react
    restart: always
    networks:
      - smartnet

  nginx:
    image: nginx:1.25
    container_name: nginx-smart
    restart: always
    depends_on:
      - frontend-react
      - backend-spring
    ports:
      - "80:80"
    volumes:
      - ../smart-react-vite-final/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - smartnet

volumes:
  mysql_data:

networks:
  smartnet:
    driver: bridge
