services:
  nginx:
    image: nginx:1.23
    volumes:
      - ../smart-react-vite-final/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/vnptbacninh.com:/etc/letsencrypt/live/vnptbacninh.com:ro
      - /etc/letsencrypt/archive/vnptbacninh.com:/etc/letsencrypt/archive/vnptbacninh.com:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend-spring
    restart: always

  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=smart
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-spring:
    build:
      context: ../smart-java-spring-final
      dockerfile: Dockerfile
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/smart
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - PROJECT_UPLOAD_FILE_BASE_URI=file:///uploads/
    volumes:
      - ../upload-docker/:/uploads/
    restart: always

volumes:
  mysql-data:
